
actionWithUsers.py::test_sealTest[44510b5ce8f35d37c5f5a88712108335qweDelimqwe1649230043qweDelimqweroot-0] 
-------------------------------- live log call ---------------------------------
INFO     root:actionWithUsers.py:32 Try to create new test account
INFO     root:actionWithUsers.py:36 Account created and take id -> user13
INFO     root:actionWithUsers.py:43 Try to login on new test account
INFO     root:actionWithUsers.py:49 Login successfully
INFO     root:actionWithUsers.py:69 Try to login back
INFO     root:actionWithUsers.py:78 Login back sucessfully, new seal -> 91e754628c642eefaff0a11f76f4a901
INFO     root:actionWithUsers.py:53 Try to disable new test account
INFO     root:actionWithUsers.py:56 Disabled sucessfully
INFO     root:actionWithUsers.py:59 Try to delete new test account
INFO     root:actionWithUsers.py:62 Delete sucessfully
PASSED

============================== 1 passed in 0.35s ===============================
