
No_Login_rest_access_get_group_paths.py::test_start[0] 
-------------------------------- live log call ---------------------------------
INFO     root:No_Login_rest_access_get_group_paths.py:16 Trying -> /rest/access/get_group_paths
INFO     root:waiter.py:26 Waiting rest response to be changed...
INFO     root:waiter.py:26 Waiting rest response to be changed...
INFO     root:waiter.py:26 Waiting rest response to be changed...
FAILED

=================================== FAILURES ===================================
________________________________ test_start[0] _________________________________

debugLevel = '0'

    @allure.title("No login _rest_access_get_group_paths method check")
    def test_start(debugLevel):
        debugEnable(int(debugLevel))
        link = "/rest/access/get_group_paths"
        host = getFromConfig("host")
        logging.info("Trying -> " + link)
        request0 = waitGetResponseToBeChanged("http://" + host + link, "data")
        try:
>           request = waitGetResponseToBeChanged("http://" + host + link, "data").split('"message":"')[1].split('"')[0]
E           IndexError: list index out of range

No_Login_rest_access_get_group_paths.py:19: IndexError

During handling of the above exception, another exception occurred:

debugLevel = '0'

    @allure.title("No login _rest_access_get_group_paths method check")
    def test_start(debugLevel):
        debugEnable(int(debugLevel))
        link = "/rest/access/get_group_paths"
        host = getFromConfig("host")
        logging.info("Trying -> " + link)
        request0 = waitGetResponseToBeChanged("http://" + host + link, "data")
        try:
            request = waitGetResponseToBeChanged("http://" + host + link, "data").split('"message":"')[1].split('"')[0]
        except:
>           request = waitGetResponseToBeChanged("http://" + host + link, "data").split('"message": "')[1].split('"')[0]
E           IndexError: list index out of range

No_Login_rest_access_get_group_paths.py:21: IndexError
------------------------------ Captured log call -------------------------------
INFO     root:No_Login_rest_access_get_group_paths.py:16 Trying -> /rest/access/get_group_paths
INFO     root:waiter.py:26 Waiting rest response to be changed...
INFO     root:waiter.py:26 Waiting rest response to be changed...
INFO     root:waiter.py:26 Waiting rest response to be changed...
=========================== short test summary info ============================
FAILED No_Login_rest_access_get_group_paths.py::test_start[0] - IndexError: l...
========================= 1 failed in 72.61s (0:01:12) =========================
