
update_seal.py::test_start[0] 
-------------------------------- live log call ---------------------------------
INFO     root:update_seal.py:17 Trying -> /rest/account/update_seal
INFO     root:waiter.py:26 Waiting rest response to be changed...
FAILED

=================================== FAILURES ===================================
________________________________ test_start[0] _________________________________

debugLevel = '0'

    @allure.title("No login is_loggin_in method check")
    def test_start(debugLevel):
        debugEnable(int(debugLevel))
        link = "/rest/account/update_seal"
        host = getFromConfig("host")
        logging.info("Trying -> " + link)
>       request = waitGetResponseToBeChanged("http://" + host + link, "data").split('"message":"')[1].split('"')[0]
E       IndexError: list index out of range

update_seal.py:18: IndexError
------------------------------ Captured log call -------------------------------
INFO     root:update_seal.py:17 Trying -> /rest/account/update_seal
INFO     root:waiter.py:26 Waiting rest response to be changed...
=========================== short test summary info ============================
FAILED update_seal.py::test_start[0] - IndexError: list index out of range
============================== 1 failed in 26.94s ==============================
